name: Echo "Hello World" on Merged PR with Grant Label and Codeowner

on:
  pull_request_review:
    types:
      - submitted
  pull_request:
    types:
      - closed

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Extract "Address" value from PR description
        id: address
        run: |
          PR_DESCRIPTION=$(curl -s "${{ github.event.pull_request.url }}" | jq -r '.body')
          ADDRESS_VALUE=$(echo "${PR_DESCRIPTION}" | grep -ioP '(?<=Address: ).*')
          echo "::set-output name=ADDRESS_VALUE::${ADDRESS_VALUE}"
          echo "Address"
          echo "${ADDRESS_VALUE}"
          echo "PR Description:"
          echo "${PR_DESCRIPTION}"
          
          ISSUE_NUMBER=$(echo "${PR_DESCRIPTION}" | grep -ioP 'closes\s+#\d+' | grep -oP '\d+')
          echo "Issue Number:"
          echo "${ISSUE_NUMBER}"

          ISSUE_LABELS=$(curl -s "${{ github.repository }}/issues/${ISSUE_NUMBER}" | jq -r '.labels[] | select(.name == "grant")')
          echo "Labels: "
          echo "${ISSUE_LABELS}"
          
          

