name: Echo "Hello World" on Merged PR with Grant Label and Codeowner

on:
  pull_request_review:
    types:
      - submitted
  pull_request:
    types:
      - closed

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Extract "Address" value from PR description
        id: address
        run: |
          PR_DESCRIPTION=$(curl -s "${{ github.event.pull_request.url }}" | jq -r '.body')
          ADDRESS_VALUE=$(echo "${PR_DESCRIPTION}" | grep -ioP '(?<=Address: ).*')
          echo "::set-output name=ADDRESS_VALUE::${ADDRESS_VALUE}"
          echo "Address"
          echo "${ADDRESS_VALUE}"
          echo "PR Description:"
          echo "${PR_DESCRIPTION}"
          
          ISSUE_NUMBER=$(echo "${PR_DESCRIPTION}" | grep -ioP 'closes\s+#\d+' | grep -oP '\d+')
          echo "Issue Number:"
          echo "${ISSUE_NUMBER}"

          ISSUE_TIMELINE=$(curl -s "${{ github.event.repository.url }}/issues/${ISSUE_NUMBER}/timeline")
          GRANT_ASSIGNER=$(echo "${ISSUE_TIMELINE}" | jq '.[] | select(.event == "labeled") | .actor.login')
          echo "grant assigner: "
          echo "${GRANT_ASSIGNER}"
          
          echo "::set-output name=GRANT_ASSIGNER::${GRANT_ASSIGNER}"
          
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check CODEOWNERS
        run: |
          username=${{ steps.address.outputs.GRANT_ASSIGNER }}
          if grep -q "^.*\s$username$" CODEOWNERS; then
            echo "User $username is a codeowner."
            exit 0
          else
            echo "User $username is not a codeowner."
            exit 1
          fi
          

